import { PackDefinition } from "./index"

export const tutoringPack: PackDefinition = {
  id: "tutoring",
  name: "Tutoring Operations",
  version: "1.0.0",
  description: "Complete tutoring business management with students, teachers, sessions, payments, and entitlements",
  author: "Struere",
  license: "MIT",
  entityTypes: [
    {
      name: "Teacher",
      slug: "teacher",
      description: "A tutor who conducts sessions",
      schema: {
        type: "object",
        properties: {
          name: { type: "string" },
          email: { type: "string", format: "email" },
          phone: { type: "string" },
          subjects: { type: "array", items: { type: "string" } },
          availability: {
            type: "object",
            properties: {
              monday: { type: "array", items: { type: "number" } },
              tuesday: { type: "array", items: { type: "number" } },
              wednesday: { type: "array", items: { type: "number" } },
              thursday: { type: "array", items: { type: "number" } },
              friday: { type: "array", items: { type: "number" } },
              saturday: { type: "array", items: { type: "number" } },
              sunday: { type: "array", items: { type: "number" } },
            },
          },
          hourlyRate: { type: "number" },
          bio: { type: "string" },
          userId: { type: "string" },
        },
        required: ["name", "email"],
      },
      searchFields: ["name", "email", "subjects"],
      displayConfig: {
        listFields: ["name", "email", "subjects"],
        detailFields: ["name", "email", "phone", "subjects", "availability", "bio"],
      },
    },
    {
      name: "Student",
      slug: "student",
      description: "A learner receiving tutoring",
      schema: {
        type: "object",
        properties: {
          name: { type: "string" },
          grade: { type: "string" },
          subjects: { type: "array", items: { type: "string" } },
          notes: { type: "string" },
          preferredTeacherId: { type: "string" },
          guardianId: { type: "string" },
        },
        required: ["name"],
      },
      searchFields: ["name", "grade"],
      displayConfig: {
        listFields: ["name", "grade", "subjects"],
        detailFields: ["name", "grade", "subjects", "notes", "preferredTeacherId"],
      },
    },
    {
      name: "Guardian",
      slug: "guardian",
      description: "Parent or guardian responsible for payment and communication",
      schema: {
        type: "object",
        properties: {
          name: { type: "string" },
          email: { type: "string", format: "email" },
          phone: { type: "string" },
          whatsappNumber: { type: "string" },
          billingAddress: {
            type: "object",
            properties: {
              street: { type: "string" },
              city: { type: "string" },
              postalCode: { type: "string" },
              country: { type: "string" },
            },
          },
          paymentMethod: { type: "string" },
          userId: { type: "string" },
        },
        required: ["name", "phone"],
      },
      searchFields: ["name", "email", "phone"],
      displayConfig: {
        listFields: ["name", "email", "phone"],
        detailFields: ["name", "email", "phone", "whatsappNumber", "billingAddress"],
      },
    },
    {
      name: "Session",
      slug: "session",
      description: "A scheduled tutoring session",
      schema: {
        type: "object",
        properties: {
          teacherId: { type: "string" },
          studentId: { type: "string" },
          guardianId: { type: "string" },
          startTime: { type: "number" },
          duration: { type: "number" },
          subject: { type: "string" },
          meetingLink: { type: "string" },
          status: {
            type: "string",
            enum: ["pending_payment", "scheduled", "in_progress", "completed", "cancelled", "no_show"],
          },
          entitlementId: { type: "string" },
          paymentId: { type: "string" },
          teacherNotes: { type: "string" },
          guardianNotes: { type: "string" },
          reportSubmitted: { type: "boolean" },
          reportContent: { type: "string" },
          cancellationReason: { type: "string" },
          cancelledBy: { type: "string" },
          cancelledAt: { type: "number" },
        },
        required: ["teacherId", "studentId", "startTime", "duration"],
      },
      searchFields: ["subject"],
      displayConfig: {
        listFields: ["startTime", "studentId", "teacherId", "status"],
        detailFields: ["startTime", "duration", "subject", "meetingLink", "status", "teacherNotes"],
      },
    },
    {
      name: "Payment",
      slug: "payment",
      description: "A payment record for sessions or packs",
      schema: {
        type: "object",
        properties: {
          guardianId: { type: "string" },
          amount: { type: "number" },
          currency: { type: "string" },
          status: {
            type: "string",
            enum: ["pending", "processing", "paid", "failed", "refunded"],
          },
          method: { type: "string" },
          providerReference: { type: "string" },
          sessionId: { type: "string" },
          entitlementId: { type: "string" },
          paymentLinkUrl: { type: "string" },
          paidAt: { type: "number" },
          failedAt: { type: "number" },
          failureReason: { type: "string" },
        },
        required: ["guardianId", "amount", "status"],
      },
      searchFields: [],
      displayConfig: {
        listFields: ["guardianId", "amount", "status", "paidAt"],
        detailFields: ["guardianId", "amount", "currency", "status", "method", "providerReference"],
      },
    },
    {
      name: "Entitlement",
      slug: "entitlement",
      description: "A pack of session credits",
      schema: {
        type: "object",
        properties: {
          guardianId: { type: "string" },
          studentId: { type: "string" },
          totalCredits: { type: "number" },
          remainingCredits: { type: "number" },
          usedCredits: { type: "number" },
          expiresAt: { type: "number" },
          status: {
            type: "string",
            enum: ["active", "exhausted", "expired", "cancelled"],
          },
          paymentId: { type: "string" },
          subject: { type: "string" },
          preferredTeacherId: { type: "string" },
          recurringSchedule: {
            type: "object",
            properties: {
              dayOfWeek: { type: "number" },
              hour: { type: "number" },
              minute: { type: "number" },
            },
          },
        },
        required: ["guardianId", "studentId", "totalCredits", "remainingCredits"],
      },
      searchFields: [],
      displayConfig: {
        listFields: ["studentId", "totalCredits", "remainingCredits", "status"],
        detailFields: ["studentId", "totalCredits", "remainingCredits", "usedCredits", "expiresAt", "status"],
      },
    },
  ],
  roles: [
    {
      name: "admin",
      description: "Full access to all operations",
      isSystem: true,
      policies: [
        { resource: "*", actions: ["create", "read", "update", "delete", "list"], effect: "allow", priority: 100 },
      ],
    },
    {
      name: "teacher",
      description: "Tutors who conduct sessions",
      isSystem: false,
      policies: [
        { resource: "session", actions: ["list", "read", "update"], effect: "allow", priority: 50 },
        { resource: "student", actions: ["read"], effect: "allow", priority: 50 },
        { resource: "teacher", actions: ["read", "update"], effect: "allow", priority: 50 },
        { resource: "payment", actions: ["read", "list", "create", "update", "delete"], effect: "deny", priority: 100 },
        { resource: "entitlement", actions: ["read", "list", "create", "update", "delete"], effect: "deny", priority: 100 },
        { resource: "guardian", actions: ["read", "list", "create", "update", "delete"], effect: "deny", priority: 100 },
      ],
    },
    {
      name: "guardian",
      description: "Parents/guardians who manage students and payments",
      isSystem: false,
      policies: [
        { resource: "session", actions: ["list", "read"], effect: "allow", priority: 50 },
        { resource: "student", actions: ["read", "update"], effect: "allow", priority: 50 },
        { resource: "guardian", actions: ["read", "update"], effect: "allow", priority: 50 },
        { resource: "payment", actions: ["list", "read"], effect: "allow", priority: 50 },
        { resource: "entitlement", actions: ["list", "read"], effect: "allow", priority: 50 },
        { resource: "teacher", actions: ["read"], effect: "allow", priority: 50 },
        { resource: "*", actions: ["create", "delete"], effect: "deny", priority: 100 },
      ],
    },
  ],
  scopeRules: [
    {
      roleName: "teacher",
      entityTypeSlug: "session",
      type: "field",
      field: "data.teacherId",
      operator: "eq",
      value: "actor.userId",
    },
    {
      roleName: "teacher",
      entityTypeSlug: "teacher",
      type: "field",
      field: "data.userId",
      operator: "eq",
      value: "actor.userId",
    },
    {
      roleName: "guardian",
      entityTypeSlug: "session",
      type: "field",
      field: "data.guardianId",
      operator: "eq",
      value: "actor.userId",
    },
    {
      roleName: "guardian",
      entityTypeSlug: "student",
      type: "field",
      field: "data.guardianId",
      operator: "eq",
      value: "actor.userId",
    },
    {
      roleName: "guardian",
      entityTypeSlug: "guardian",
      type: "field",
      field: "data.userId",
      operator: "eq",
      value: "actor.userId",
    },
    {
      roleName: "guardian",
      entityTypeSlug: "payment",
      type: "field",
      field: "data.guardianId",
      operator: "eq",
      value: "actor.userId",
    },
    {
      roleName: "guardian",
      entityTypeSlug: "entitlement",
      type: "field",
      field: "data.guardianId",
      operator: "eq",
      value: "actor.userId",
    },
  ],
  fieldMasks: [
    { roleName: "teacher", entityTypeSlug: "session", fieldPath: "data.guardianId", maskType: "hide" },
    { roleName: "teacher", entityTypeSlug: "session", fieldPath: "data.paymentId", maskType: "hide" },
    { roleName: "teacher", entityTypeSlug: "session", fieldPath: "data.entitlementId", maskType: "hide" },
    { roleName: "teacher", entityTypeSlug: "session", fieldPath: "data.guardianNotes", maskType: "hide" },
    { roleName: "teacher", entityTypeSlug: "session", fieldPath: "data.cancellationReason", maskType: "hide" },
    { roleName: "teacher", entityTypeSlug: "session", fieldPath: "data.cancelledBy", maskType: "hide" },
    { roleName: "teacher", entityTypeSlug: "student", fieldPath: "data.notes", maskType: "hide" },
    { roleName: "teacher", entityTypeSlug: "student", fieldPath: "data.guardianId", maskType: "hide" },
    { roleName: "guardian", entityTypeSlug: "session", fieldPath: "data.teacherNotes", maskType: "hide" },
    { roleName: "guardian", entityTypeSlug: "session", fieldPath: "data.reportContent", maskType: "hide" },
    { roleName: "guardian", entityTypeSlug: "teacher", fieldPath: "data.hourlyRate", maskType: "hide" },
    { roleName: "guardian", entityTypeSlug: "teacher", fieldPath: "data.userId", maskType: "hide" },
  ],
  migrations: [],
}
